# Generated by Django 3.2.7 on 2021-09-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notable_actors', models.TextField()),
                ('network', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('rating', models.PositiveIntegerField(null=True)),
                ('photo_url', models.TextField()),
            ],
        ),
    ]
