# Generated by Django 3.2.7 on 2021-09-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotten_potatoes', '0002_alter_show_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='photo_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
