# Generated by Django 3.2.7 on 2021-09-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotten_potatoes', '0003_alter_show_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='photo_url',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
